# docker-compose.yml for GridTrader Pro
version: '3.8'

services:
  gridtrader-pro:
    build: .
    container_name: gridtrader-pro
    restart: unless-stopped
    
    # Environment variables
    environment:
      - ENVIRONMENT=production
      - DATABASE_PATH=/app/data/gridtrader_clients.db
      - LOG_LEVEL=INFO
    
    # Environment file for secrets
    env_file:
      - .env.production
    
    # Volume mounts for persistence
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "final_fixed_test_runner.py"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 2m
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Optional: Add monitoring
  monitoring:
    image: prom/prometheus:latest
    container_name: gridtrader-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gridtrader-pro

networks:
  default:
    name: gridtrader-network
